# Generated by Django 3.1.3 on 2020-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201125_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='word',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
