# Generated by Django 3.1.3 on 2020-11-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201125_0124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
